In [3]:
import numpy

In [5]:
numpy.array([1,2,3,True])

array([1, 2, 3, 1])

In [6]:
numpy.array([1,2,3,False])

array([1, 2, 3, 0])

In [7]:
numpy.array([1,2,3,'numpy'])

array(['1', '2', '3', 'numpy'], dtype='<U21')

In [8]:
numpy.array([1,2,3,3.2,5.6])

array([1. , 2. , 3. , 3.2, 5.6])

In [9]:
numpy.array([1,2,3,3.2])

array([1. , 2. , 3. , 3.2])